extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_Area_1_macro_objs[];
extern Vtx bob_dl_Cosa_mesh_vtx_0[83];
extern Gfx bob_dl_Cosa_mesh_tri_0[];
extern Vtx bob_dl_Cosa_mesh_vtx_1[54];
extern Gfx bob_dl_Cosa_mesh_tri_1[];
extern Vtx bob_dl_Cosa_mesh_vtx_2[222];
extern Gfx bob_dl_Cosa_mesh_tri_2[];
extern Vtx bob_dl_Cosa_mesh_vtx_3[66];
extern Gfx bob_dl_Cosa_mesh_tri_3[];
extern Vtx bob_dl_Cosa_mesh_vtx_4[18];
extern Gfx bob_dl_Cosa_mesh_tri_4[];
extern Vtx bob_dl_Cosa_mesh_vtx_5[58];
extern Gfx bob_dl_Cosa_mesh_tri_5[];
extern Vtx bob_dl_Cosa_mesh_vtx_6[30];
extern Gfx bob_dl_Cosa_mesh_tri_6[];
extern Vtx bob_dl_Cosa_mesh_vtx_7[101];
extern Gfx bob_dl_Cosa_mesh_tri_7[];
extern Vtx bob_dl_Cosa_mesh_vtx_8[28];
extern Gfx bob_dl_Cosa_mesh_tri_8[];
extern Vtx bob_dl_Cosa_mesh_vtx_9[8];
extern Gfx bob_dl_Cosa_mesh_tri_9[];
extern Vtx bob_dl_Cosa_mesh_vtx_10[32];
extern Gfx bob_dl_Cosa_mesh_tri_10[];
extern Vtx bob_dl_Cosa_mesh_vtx_11[61];
extern Gfx bob_dl_Cosa_mesh_tri_11[];
extern Vtx bob_dl_Cosa_mesh_vtx_12[64];
extern Gfx bob_dl_Cosa_mesh_tri_12[];
extern Vtx bob_dl_Cosa_mesh_vtx_13[601];
extern Gfx bob_dl_Cosa_mesh_tri_13[];
extern Vtx bob_dl_Cosa_mesh_vtx_14[153];
extern Gfx bob_dl_Cosa_mesh_tri_14[];
extern Vtx bob_dl_Cosa_mesh_vtx_15[116];
extern Gfx bob_dl_Cosa_mesh_tri_15[];
extern Vtx bob_dl_Cosa_mesh_vtx_16[36];
extern Gfx bob_dl_Cosa_mesh_tri_16[];
extern Vtx bob_dl_Cosa_mesh_vtx_17[81];
extern Gfx bob_dl_Cosa_mesh_tri_17[];
extern Vtx bob_dl_Cosa_mesh_vtx_18[54];
extern Gfx bob_dl_Cosa_mesh_tri_18[];
extern Vtx bob_dl_Cosa_mesh_vtx_19[55];
extern Gfx bob_dl_Cosa_mesh_tri_19[];
extern Vtx bob_dl_Cosa_mesh_vtx_20[58];
extern Gfx bob_dl_Cosa_mesh_tri_20[];
extern Vtx bob_dl_Cosa_mesh_vtx_21[24];
extern Gfx bob_dl_Cosa_mesh_tri_21[];
extern Vtx bob_dl_Cosa_mesh_vtx_22[6];
extern Gfx bob_dl_Cosa_mesh_tri_22[];
extern Vtx bob_dl_Cosa_mesh_vtx_23[3];
extern Gfx bob_dl_Cosa_mesh_tri_23[];
extern Vtx bob_dl_Cosa_mesh_vtx_24[20];
extern Gfx bob_dl_Cosa_mesh_tri_24[];
extern Vtx bob_dl_Cosa_mesh_vtx_25[104];
extern Gfx bob_dl_Cosa_mesh_tri_25[];

extern Gfx bob_dl_Cosa_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

